### ISSUE TITLE
Single cabal file?

### ISSUE THREAD

**Issue by hamishmack** [ElvishJerricco/reflex-project-skeleton#1]
I wonder if it is necessary to have 3 cabal files?  I think it might be better (at least for small projects) to have a single `reflex-project-skeleton.cabal` file. With:

* **library** - `hs-source-dirs: src` with all the code needed for the frontend except the jsaddle runners.
* **executable frontend** - `hs-source-dirs: src-main` and `build-depends: reflex-project-skeleton`.  Code in `src-main` just has main modules adding the runners.
* **executable backend** - `hs-source-dirs: src-backend` and `build-depends: reflex-project-skeleton`.   The `src-backend` has any modules that are only needed on the backend.

Making sure the executables do not reference the `src` dir of the library directly (otherwise the library code is likely to be recompiled unnecessarily).

Not sure if the main module for the backend would go in `src-main` or `src-backend` (either would work).

**Comment by ElvishJerricco** [comment]
While this is definitely a viable option for many people, splitting into multiple packages is something a lot of people prefer to do, and I wanted to show that such a workflow doesn’t have to be so bad with Nix (at least it won’t be once I push the new `project` format). Plus, having distinct Nix derivations for each package is somewhat useful.

**Comment by ElvishJerricco** [comment]
Closing
