### ISSUE TITLE
Should build without an internet connection

### ISSUE THREAD

**Issue by mightybyte** [ElvishJerricco/reflex-project-skeleton#10]
Today I discovered I can't build reflex-project-skeleton without an internet connection.  I had built it successfully with an internet connection, so all the dependencies were there and nothing needed to be downloaded.  Therefore it shouldn't have needed to have an internet connection.

**Comment by ElvishJerricco** [comment]
Could you specify what broke? I'm able to build without internet. I can even add a dependency to my cabal file if it already exists in my nix store.

**Comment by mightybyte** [comment]
It was failing on nix-build.

```
$ nix-build
download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/c2rlyhznby5vdbfinzcyfi9766hnpl7v.narinfo’ (Curl error 6)
download-via-ssh: ssh: Could not resolve hostname hydra.dev.somatix.ai: nodename nor servname provided, or not known
download-via-ssh: error: unexpected end-of-file
error: substituter ‘download-via-ssh’ died unexpectedly
```

But I just tried nix-shell and that works.  Maybe the nix-build issue has something to do with nix and not this skeleton?

**Comment by ElvishJerricco** [comment]
Hm. Looks like that has something to do with your binary caches. I would consider that a bug in the `download-via-ssh` binary cache substituter. It looks like it checks to see if it can get the build from your SSH-based binary cache, then fails un-gracefully.

**Comment by ElvishJerricco** [comment]
You can work around this using `--option` on the command line to [set options](https://nixos.org/nix/manual/#description-45) to avoid using the cache. I think you'll want one of these options: `build-use-substitutes`, `build-fallback`, or `use-binary-caches`.

**Comment by mightybyte** [comment]
Ahh.  `nix-build --option build-use-substitutes false` seems to do the trick.  Brutal to remember though.
