### ISSUE TITLE
Way to extend generalDevTools in project-skeleton?

### ISSUE THREAD

**Issue by gspia** [ElvishJerricco/reflex-project-skeleton#3]
Is there an easy way to extend generalDevTools with the default.nix file of this project skeleton?

Some people have asked about the different editor tools like dante, ghc-mod, etc. lately and maybe there are some other tools people would like to use as per project (and not as a user wide or as a global installation). 

If it is already doable easily, maybe a tiny update to documentation then? (For example, at the moment it is easier to me to add tools to the default.nix of reflex-platform into the generalDevTools declaration than to try to extend/override the project definitions. And this of course is quite bad thing to do.)

(Btw, I think that the documentation is suberb for the skeleton and  the project-part in platform.)

**Comment by ElvishJerricco** [comment]
There isn’t currently a way to do that, but good idea! What do you think the syntax should look like?

**Comment by gspia** [comment]
Maybe something like
  additionalTools = [ nhp.hdevtools nhp.ghc-mod nhp.dante pkgs.othertool];
but is it doable? The nhp would be a shorthand to nativeHaskellPackages and pkgs to nixpkgs. Or if these just cause more confusion, I'll guess that people would be happy to type 
  additionalTools = [ nativeHaskellPackages.hdevtools nativeHaskellPackages.ghc-mod nativeHaskellPackages.dante nixpkgs.othertool];

Is additionalTools ok name? generalDevToolAdds?

**Comment by ElvishJerricco** [comment]
Yea, something I'm kind of worried about is simplicity. The main purpose of this repo, and the `project` format in general, is to keep things as simple as possible. So while I think the most useful thing would be:

```nix
  shells = {
    ghc = {
      packages = ["common" "frontend" "backend"];
      tools = haskellPackages: [ ... ];
    };
  };
```

This is definitely stretching the simplicity beyond where I would like it. On the simplicity extreme, I think we'd be looking at something like this:

```nix
(import ./reflex-platform {}).project ({ pkgs, nativeHaskellPackages, ... }: {
  ...

  tools = [ ... ];
})
```

But it lacks nuance; i.e. you can't have different tools depending on the shell this way.

**Comment by gspia** [comment]
I would buy the first one, where `tools` is inside `ghc` attribute as I believe that given an example, many people were able to modify it to their needs. And it would also shed (at least a bit) light on the fact that ghc and ghcjs require and in a way give different tool sets to work with. 

There could be two simple tool extending examples: one for emacs and the other for vim/nvim users. Don't know if the atom landom has its own tools but people would be able to change the examples.

Do you know of any typical tools that ghcjs users probably would like to use? And not yet present in the platform that seams to include nodejs and closurecompiler, I was thinking if there could be a nice example for ghcjs, too.

**Comment by ElvishJerricco** [comment]
https://github.com/reflex-frp/reflex-platform/pull/199
