### ISSUE TITLE
Please explain how to create the link to the reflex-platform project

### ISSUE THREAD

**Issue by hansroland** [ElvishJerricco/reflex-project-skeleton#4]
Please explain, how you created the link to the reflex-dom-platform project on Github. This link is a very important part of your project. I think this is advanced Linux / Github usage.  
Many thanks!

**Comment by ElvishJerricco** [comment]
Yea, look into git submodules. That's all it is in this case. But it doesn't *have* to be. You can just clone reflex-platform anywhere, as long as you reflect that path properly in `default.nix`

**Comment by hansroland** [comment]
That helps, many thanks!
