### ISSUE TITLE
git submodule vs reflex-platform path (a documentation thing)

### ISSUE THREAD

**Issue by gspia** [ElvishJerricco/reflex-project-skeleton#5]
Hi!
How about adding a short note about
`git pull && git submodule update --init --recursive`
or something similar? This may not be that obvious to the people who have just started with git.

Another things that could be mentioned at the time is that other possibility is to update the path in the default.nix. 

E.g. somewhere text like

Project-skeleton and reflex-platform
--
After git cloning this repo, in order to use reflex-project-skeleton, you should either update the git submodule with
```git pull && git submodule update --init --recursive```
or change the platform path in the default.nix to point where you have downloaded the reflex-platform.
E.g., if it is at `~/Reflex/reflex-platform/` change line
`(import ./reflex-platform {}).project ({ pkgs, ... }: {`
in the default.nix to
`(import ~/Reflex/reflex-platform {}).project ({ pkgs, ... }: {`

**Comment by ElvishJerricco** [comment]
How's that?
