### ISSUE TITLE
proposal about git submodule updates

### ISSUE THREAD

**Issue by gspia** [ElvishJerricco/reflex-project-skeleton#6]
Hi, 
Since time passes, the submodule reference becomes old, and people may want to update them.

How about adding (somewhere) a bit info about a git cmd that can do it with suitable warnings? Maybe something like
```
git submodule foreach "(git checkout develop; git pull --recurse-submodules)&"
```
And the warning text should be about the branch, which is develop above. (Yeah, I took the master-branch couple of moments ago, which gave a bit surprising results.)

If not suitable in here, how about in the "project"-docs?

**Comment by ElvishJerricco** [comment]
Frankly, I don't think reflex should be in the business of git tutorials. I just think it's out of scope. Might be worthwhile to have a link to git's docs about submodules in the project doc though.

**Comment by mightybyte** [comment]
Would it be possible to ditch the submodule entirely?  I've used submodules a fair amount and they get the job done, but I often find that I would rather just refer to a specific git hash.

**Comment by ElvishJerricco** [comment]
@mightybyte How would we do that? Do you mean import `reflex-platform` nix-style, with `fetchFromGitHub` or something?

**Comment by mightybyte** [comment]
Yeah.  I haven't looked into the details of how you're using reflex-platform in this package, but I was thinking something along those lines.

**Comment by ElvishJerricco** [comment]
@mightybyte I originally wanted to avoid that because I didn't want to add some arcane lines of Nix that might confuse newcomers. Submodules seemed less likely to confuse people, since more people know git than Nix.

**Comment by gspia** [comment]
Links to git docs sounds good to me. (And people who are really interested in updating the submodules will find the information, if they want to. So maybe it is ok to close this proposal.)

About that submodules vs. fetchfromGitHub or something: one way, and I think quite natural, is to think that user installs `reflex-platform` seperately and then gives a path to it, e.g., in the `default-nix`. This way the updating would be easy and separate thing for the skeleton and platform.

But yeah, when people take their first trials, they probably take the skeleton and start modifying it. Probably they can change the path to platform as well if feeling that it is easier way to update the 
platform than using submodules.

**Comment by mightybyte** [comment]
I think the problem with using a path for `reflex-platform` is that it's not purely functional.  If all you have is a path, you don't know what version that path was at.  `fetchFromGitHub` nails it down.  I've never found `fetchFromGitHub` lines arcane, but rather quite understandable and obvious how to modify.
