### ISSUE TITLE
Switch to a different LICENSE more appropriate for project templates

### ISSUE THREAD

**Issue by mightybyte** [ElvishJerricco/reflex-project-skeleton#8]
I usually like the BSD3 license and use it for most of my projects, but for this one I almost think it would be better to use a different license or no license at all.  It's not that BSD3 is incompatible with the idea of a project template, but rather that the "must retain the above copyright notice" clauses are kind of annoying for people basing their project off this template whether they intend it to be open source or not.  What do you think?  IANAL, so I really don't know what to recommend here beyond saying that it makes me a little hesitant to use it as the basis for my projects.  What about something like the legal equivalent of something simple like "By using this, you agree not to sue me, and you can remove this LICENSE and replace it with your own."?

**Comment by ElvishJerricco** [comment]
Yea I agree. If someone can give me something precise that I should use, I'd be happy to switch.

**Comment by mightybyte** [comment]
This looks good: https://choosealicense.com/licenses/#unlicense

I found it by going to https://choosealicense.com and clicking through the obvious path.

**Comment by ElvishJerricco** [comment]
Looks good to me.
